### ISSUE TITLE
刷入模块失败

### ISSUE THREAD

**Issue by Mubai-meng** [LxDebug/DarkP#10]
小米12s
Android13
MIUI14
![Screenshot_2023-01-15-23-27-12-081_com.topjohnwu.magisk.jpg](https://user-images.githubusercontent.com/86759349/212550275-c9ed743d-31e1-40de-80f4-629fb6a796f5.jpg)

**Comment by f1owkang** [comment]
有详细的报错嘛

**Comment by Mubai-meng** [comment]
> 有详细的报错嘛

没，可能是自动构建的问题，手动下载源码压缩打包可以刷入

**Comment by f1owkang** [comment]
好滴好滴

**Comment by LxDebug** [comment]
好滴好滴
