### ISSUE TITLE
magisk delta 无法使用模块

### ISSUE THREAD

**Issue by sakana164** [LxDebug/DarkP#11]
可以刷上，但是设置界面还是跟没刷一样，我其他模块都正常，可以解决嘛？
k40，MIUI14 
V14.0.23.4.2.DEV 开发版
安卓13

**Comment by f1owkang** [comment]
有可能是系统版本问题，目前没有办法解决

**Comment by sakana164** [comment]
> 有可能是系统版本问题，目前没有办法解决

不是系统版本问题，好像就是因为换了delta
