### ISSUE TITLE
设置自带的通知历史记录

### ISSUE THREAD

**Issue by TGW555** [LxDebug/DarkP#14]
不能显示深色模式
![Screenshot_2023-07-07-14-10-31-316_com android settings](https://github.com/LxDebug/DarkP/assets/29172047/d480333e-1008-4d58-8c84-71d0c8466f67)
看不清楚。

希望能够快速支持。

进入这个路径的方法用创建快捷方式。

**Comment by TGW555** [comment]
开发者有处理这个问题的想法吗？
等待中。

**Comment by f1owkang** [comment]
这个页面定位不到，抱歉很晚回复

**Comment by TGW555** [comment]
> 这个页面定位不到，抱歉很晚回复

隐启设置app，首页>状态栏>通知历史记录

**Comment by TGW555** [comment]
> 

创建快捷方式app有时候半天才加载出来这个页面的路径，有时候可以直接打开，有时候要用root的方式才能够打开这个页面。
![Screenshot_2023-07-18-19-02-44-011_com x7890 shortcutcreator-edit](https://github.com/LxDebug/DarkP/assets/29172047/4c26c7da-4e41-4baa-aa3c-8078fadb649e)

**Comment by f1owkang** [comment]
这个页面是隐藏的，我的技术不够不好处理，不好意思

**Comment by TGW555** [comment]
> 这个页面是隐藏的，我的技术不够不好处理，不好意思
好的，看来只能官方改了。
