### ISSUE TITLE
刷入后深色模式设置里没有新增应用

### ISSUE THREAD

**Issue by CorkFyv** [LxDebug/DarkP#17]
K30 Pro移植版MIUI23.6.13安卓13，德尔塔26.1。刷入后没有新增应用，没有拼多多和米游社深色![Screenshot_2023-09-10-10-23-09-089_com.android.settings.jpg](https://github.com/Kslpix/DarkMode_Evolution/assets/68682502/417f1beb-2990-4d46-ba10-2443fe53f6e8)

**Comment by f1owkang** [comment]
看样子是没有替换到目录里，不确定是不是深色换文件夹了
