### ISSUE TITLE
小米深色配置.xlsx

### ISSUE THREAD

**Issue by LizzyVZ** [LxDebug/DarkP#18]
作者能否单独提供一下 小米深色配置.xlsx

**Comment by f1owkang** [comment]
这个在旧的提交记录中有，但是请注意，配置详情可能已经过期了

**Comment by f1owkang** [comment]
https://github.com/Kslpix/DarkMode_Evolution/blob/fa7281c27bc2b1e48ecb25c4963df5296fd8fca0/%E5%B0%8F%E7%B1%B3%E6%B7%B1%E8%89%B2%E9%85%8D%E7%BD%AE.xlsx
