### ISSUE TITLE
想请教一下自己添加的方法

### ISSUE THREAD

**Issue by langkiss** [LxDebug/DarkP#19]
按教程添加了之后深色模式更多中直接不显示应用，更改前显示的也丢了。已确认校验无问题，之前magisk成功修改过，最近换了ksu，这个会有影响吗

**Comment by f1owkang** [comment]
理论来说，本模块只是简单替换文件而已，应该只与系统版本有关

**Comment by langkiss** [comment]
谢谢解答，那我再试一下，之前是成功了的，只是更新完之后原有的文件被删掉了，现在就是哪怕我只在里面删掉一个包名中的字母，都会导致所有的软件都不显示了。
