### ISSUE TITLE
希望能够适配gboard和讯飞输入法的实体键盘

### ISSUE THREAD

**Issue by FEI352** [LxDebug/DarkP#20]
![Screenshot_2023-12-14-01-05-35-586_com drakeet purewriter 1](https://github.com/Kslpix/DarkMode_Evolution/assets/104716040/26884dbf-0e9b-4a00-b844-cc37d2e686ef)

用了自己试着copy一下，独阅读小说，远离手机这种直接成功了，但是讯飞输入法除了应用界面变成暗色，和gboard一样实体键盘还是原本的白天时候的颜色。

**Comment by f1owkang** [comment]
这种界面一般很难搞定的，要用到高级配置文件。目前澎湃系统已发布，我还在观望，暂时没有精力更新😰

**Comment by FEI352** [comment]
> 这种界面一般很难搞定的，要用到高级配置文件。目前澎湃系统已发布，我还在观望，暂时没有精力更新😰

谢谢大佬的回复，现在gboard的测试版已经更新了物理键盘下的md设计，以及深色背景。讯飞我也不常用，打扰你了。

**Comment by f1owkang** [comment]
好的，如果有其他问题请随时联系，close!
