### ISSUE TITLE
是否可以合并一下这个功能呢？

### ISSUE THREAD

**Issue by tonynesss** [LxDebug/DarkP#4]
添加所有已安装的所有软件到深色模式名单中。项目地址:[]()https://github.com/zhijuyingfeng/ForceDarkModeForMIUI

**Comment by MidNightBlackCat** [comment]
这个项目是读取系统安装的软件，然后写配置文件，实现机制或者思路和目的不太一样

**Comment by f1owkang** [comment]
有些应用，强制深色效果并不理想，还是建议使用名单

**Comment by tonynesss** [comment]
> 有些应用，强制深色效果并不理想，还是建议使用名单

此项目是读取用户软件并写入到白名单文件中，使得能在深色模式的强制深色设置中显示更多的应用。用户还是可以通过在深色模式设置中选择是否开启应用的强制深色的。

**Comment by f1owkang** [comment]
评估脚本后加入，感谢
